/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/fHe6LLoBmzv
 */
import { CardTitle, CardHeader, CardContent, Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import Link from "next/link";
// import { api } from "@/utils/api";

export function PrayerManagment() {
  // const data_requests = api.prayer.getAll.useQuery({});
  return (
    <div className="px-4 md:px-6 lg:px-8 py-6 space-y-6">
      <div className="space-y-2">
        <h1 className="text-3xl font-bold">Prayer Requests</h1>
        <p className="text-gray-500 dark:text-gray-400">
          Submit your prayer request below. You can also search existing
          requests or mark them as answered.
        </p>
      </div>
      <Card>
        <CardHeader>
          <div className="flex items-center justify-between w-full">
            <CardTitle>Search requests</CardTitle>
            <Button size="sm">Mark as answered</Button>
          </div>
        </CardHeader>
        <CardContent>
          <div className="flex flex-col md:flex-row items-center space-y-4 md:space-y-0 md:space-x-4">
            <Label className="sr-only" htmlFor="search">
              Search
            </Label>
            <Input
              className="max-w-xs flex-1"
              id="search"
              placeholder="Search by name or request..."
            />
            <Button className="w-full md:w-20 mt-4 md:mt-0" type="submit">
              Search
            </Button>
          </div>
        </CardContent>
      </Card>
      <Card>
        <CardHeader>
          <div className="flex items-center justify-between w-full">
            <CardTitle>Sort by</CardTitle>
            <Button size="sm">Sort</Button>
          </div>
        </CardHeader>
        <CardContent>
          <div className="space-y-4">
            <div className="flex items-center justify-between">
              <div className="flex items-center space-x-2">
                <div className="font-semibold">John Doe</div>
                <div className="text-sm text-gray-500 dark:text-gray-400">
                  2 hours ago
                </div>
              </div>
              <Link
                className="text-sm underline underline-offset-2 ml-auto"
                href="#"
              >
                View
              </Link>
            </div>
            <div className="text-sm leading-relaxed text-gray-500 dark:text-gray-400">
              Please pray for my mother who is in the hospital. She is
              undergoing surgery tomorrow. I believe in the power of prayer and
              I know that God listens to our prayers. Thank you all for your
              support.
            </div>
            <div className="flex items-center space-x-2">
              <Button className="p-2" size="sm">
                Mark as answered
              </Button>
              <Button className="p-2" size="sm">
                Assign person to prayer
              </Button>
            </div>
          </div>
          <div className="space-y-4">
            <div className="flex items-center justify-between">
              <div className="flex items-center space-x-2">
                <div className="font-semibold">Olivia Davis</div>
                <div className="text-sm text-gray-500 dark:text-gray-400">
                  1 day ago
                </div>
              </div>
              <Link
                className="text-sm underline underline-offset-2 ml-auto"
                href="#"
              >
                View
              </Link>
            </div>
            <div className="text-sm leading-relaxed text-gray-500 dark:text-gray-400">
              I am facing a difficult time in my life and I need the support of
              my brothers and sisters in Christ. Please pray for me that I may
              find peace and strength to overcome the challenges. Thank you.
            </div>
            <div className="flex items-center space-x-2">
              <Button className="p-2" size="sm">
                Mark as answered
              </Button>
              <Button className="p-2" size="sm">
                Assign person to prayer
              </Button>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
